### ISSUE TITLE
[提问] 请问文章付费后查看这个功能有在计划里吗？

### ISSUE THREAD

**Issue by inix** [luoyunchong/lin-cms-dotnetcore#14]
**描述你希望的支持的新功能？**
功能：
用户付费之后，才能查看完整内容，这个功能有在开发计划里吗？

或者能否给个实现思路？

**你期望的 API 是怎样的？**
无

**Comment by luoyunchong** [comment]
没有计划。 
付费，没有企业账号。

**Comment by inix** [comment]
> 没有计划。
> 付费，没有企业账号。

如果有企业号，大致如何实现这个功能呢？

**Comment by luoyunchong** [comment]
用一个表存用户的付费记录，关联随笔Id，在获取随笔详情页的接口上做判断，否则文章内容不获取。


付费的过程，我没做过，只做过对接后端支付，后端 也是对接第三方，比如微信支付。都有对应的SDK的。。花时间看他们的文档就行了。

**Comment by inix** [comment]
> 用一个表存用户的付费记录，关联随笔Id，在获取随笔详情页的接口上做判断，否则文章内容不获取。
> 
> 付费的过程，我没做过，只做过对接后端支付，后端 也是对接第三方，比如微信支付。都有对应的SDK的。。花时间看他们的文档就行了。

好的 谢谢
