### ISSUE TITLE
PgSql 自动创建数据库简单示例

### ISSUE THREAD

**Issue by pccai** [luoyunchong/lin-cms-dotnetcore#17]
**描述你希望的支持的新功能？**
PgSql 自动创建数据库简单示例：

         public static FreeSqlBuilder CreateDatabaseIfNotExistsPgSql(this FreeSqlBuilder @this,
            string connectionString = "")
        {
            if (connectionString == "")
            {
                connectionString = GetConnectionString(@this);
            }

            NpgsqlConnectionStringBuilder builder = new NpgsqlConnectionStringBuilder(connectionString);
            
            string createDatabaseSql =
                $"DROP DATABASE IF EXISTS \"{builder.Database}\"; CREATE DATABASE \"{builder.Database}\" WITH OWNER = \"{builder.Username}\"";
           
            using NpgsqlConnection cnn = new NpgsqlConnection(
                $"Host={builder.Host};Port={builder.Port};Username={builder.Username};Password={builder.Password};Pooling=true");
            cnn.Open();
            using (NpgsqlCommand cmd = cnn.CreateCommand())
            {
                cmd.CommandText = createDatabaseSql;
                cmd.ExecuteNonQuery();
            }

            return @this;
        }

**你期望的 API 是怎样的？**

**Comment by luoyunchong** [comment]
安装PostgreSQL 13.2, compiled by Visual C++ build 1914, 64-bit 已测试成功
