### ISSUE TITLE
代码不更新了吗？

### ISSUE THREAD

**Issue by q6781087** [luoyunchong/lin-cms-dotnetcore#24]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**
我看更新日志都懒的写了，最后的日志部分还是升级到.net5.

**Comment by luoyunchong** [comment]
还在升级lin-cms-vvlog的 vue3版本。

**Comment by luoyunchong** [comment]
一些基础包移至 https://github.com/luoyunchong/FreeKit
这个项目还没升级这些包，命名空间变化 比较多，暂未提交

**Comment by q6781087** [comment]
那我等等你？准备用这个做项目呢
