### ISSUE TITLE
好像缺了表啥的

### ISSUE THREAD

**Issue by NingLiu1998** [luoyunchong/lin-cms-dotnetcore#35]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/109678937/229030050-71bfaac7-c6c7-4159-be84-e1f91d58f312.png)

**期望的结果是什么？**
页面无报错
**实际的结果是什么？**
报错

版本是刚拉的

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/229031454-f8f9eb1d-1a55-4b1c-89de-20740ebd0c38.png)

这个没配置对，和上面Mysql配置的连接串一致

**Comment by NingLiu1998** [comment]
明白了，谢谢
