### ISSUE TITLE
直接用abp vnext就好了

### ISSUE THREAD

**Issue by xewn** [luoyunchong/lin-cms-dotnetcore#4]
我觉得直接用abp vnext的模块来开发效率要高些，后续的微服务支持也要好些？

**Comment by luoyunchong** [comment]
基于 abp vnext开发的模块，可以看这个https://blog.igeekfan.cn/2019/07/27/abp/MicroServiceDemo-iview/

从 ABP vNext 的MicroserviceDemo中修改而来，为其增加了iview的SPA界面， 实现前后端分离的用户角色授权管理功能（不是真正的微服务）

完整代码https://github.com/luoyunchong/abp/tree/master/samples/Microservice
前端项目位置https://github.com/luoyunchong/abp/tree/master/samples/Microservice/modules/app-microservice



至于ABP VNext来做微服务也不是万能药，他的功能现在还不成熟 。目前这个项目是适配一个简单的lin-cms-vue项目。三个表就能实现用户，分组，权限控制，可细化到具体的方法。
