### ISSUE TITLE
修改密码逻辑错误，修改密码不成功

### ISSUE THREAD

**Issue by WangBank** [luoyunchong/lin-cms-dotnetcore#8]
**重现步骤（可选）：**
后台登录->个人设置->修改密码 ，代码位置LinCms.Application.Cms.Users:VerifyUserPasswordAsync与ChangePasswordAsync方法
**期望的结果是什么？**
修改密码成功
**实际的结果是什么？**
输入正确密码提示密码错误，输入错误密码提示修改成功后，数据未发生改变
**已解决方案**
代码位置
LinCms.Application.Cms.Users UserService  中ChangePasswordAsync方法
public async Task ChangePasswordAsync(ChangePasswordDto passwordDto)
        {
            long currentUserId = _currentUser.Id ?? 0;

            bool valid = await _userIdentityService.VerifyUserPasswordAsync(currentUserId, passwordDto.OldPassword);
            if (!valid)
            {
                throw new LinCmsException("旧密码不正确");
            }

            await _userIdentityService.ChangePasswordAsync(currentUserId, passwordDto.NewPassword);
        }
LinCms.Application.Cms.Users：ChangePasswordAsync方法
        public async Task ChangePasswordAsync(long userId, string newpassword)
        {
            string encryptPassword = EncryptUtil.Encrypt(newpassword);
            var linUserIdentity = await _userIdentityRepository.Where(a => a.CreateUserId == userId).FirstAsync();
            linUserIdentity.Credential = encryptPassword;
            _ = _userIdentityRepository.Update(linUserIdentity);//.ExecuteUpdatedAsync();
        }
上面那个qq第三方登录，SaveQQAsync
应该是。。 IdentityType = LinUserIdentity.QQ,

**Comment by luoyunchong** [comment]
@WangBank  修改密码问题已解决。是忘记加where 判断。QQ登录已解决。之前没提交发布。

**Comment by WangBank** [comment]
好来 我再重新down一下

**Comment by luoyunchong** [comment]
可以用git clone，然后，通过 git pull更新。

**Comment by WangBank** [comment]
> 可以用git clone，然后，通过 git pull更新。

新建别的分支吗，可能会连接私有的数据库 合并会有问题 哈哈

**Comment by luoyunchong** [comment]
vs上团队资源 管理 器，设置，存储库设置，可以增加多个远程分支，本地可以 创建一个分支，然后，把源码拉取过去。

**Comment by WangBank** [comment]
> vs上团队资源 管理 器，设置，存储库设置，可以增加多个远程分支，本地可以 创建一个分支，然后，把源码拉取过去。

可能理解错我的意思了，我会把您项目中数据库链接、cap中mq链接及Model中的类有些许变化，新提交分支时怕对xxx有一定的误解影响
